# Generated by Django 3.0.5 on 2025-03-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='neighbourhood',
        ),
    ]
